name: "Deploy - IaC (Terraform)"

# run on push to main branch only
on:
  push:
    branches:
      - main
    paths:
      - "iac/terraform/**"
  workflow_dispatch:

# Using env secrets is the preferred approach for CI/CD tools. AZ login only works for user accounts and not for service principals.
env:
  ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
  WORKDIR: "iac/terraform"
  RESOURCES_PREFIX: "${{ secrets.RESOURCES_PREFIX }}" # hardcoded or dynamic based on repo name
  # LOCATION: "westus2" # hardcoded or get from secrets

# Set defaults for GitHub Actions runner
defaults:
  run:
    working-directory: "iac/terraform"

jobs:
  preview:
    name: "Preview Changes"
    runs-on: ubuntu-latest
    outputs:
      TFPLAN_EXITCODE: ${{ steps.tfplan.outputs.exitcode }}
      SECRET_BINGS-MAP-KEY: ${{ steps.getSecrets.outputs.BINGS-MAP-KEY }}
      SECRET_MSSQL-SERVER-ADM-PASSWORD: ${{ steps.getSecrets.outputs.MSSQL-SERVER-ADM-PASSWORD }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # https://learn.microsoft.com/en-us/azure/developer/github/github-key-vault
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "devopsoh51264kv"
          secrets: 'BINGS-MAP-KEY, MSSQL-SERVER-ADM-PASSWORD'
        id: getSecrets

      

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init -backend-config=resource_group_name="${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}" -backend-config=storage_account_name="${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config=container_name="${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}" -backend-config=key="${{ secrets.TFSTATE_KEY }}"

      # Generates an execution plan for Terraform
      # An exit code of 2 indicates there were changes detected and will throw an error on GitHub Action. "|| exit 0" overrides it. Just continue for now, we'll check next step
      - name: Terraform Plan
        run: terraform plan -detailed-exitcode -var="location=${{ secrets.LOCATION }}" -var="resources_prefix=${{ secrets.RESOURCES_PREFIX }}" -var="bing_maps_key=${{ steps.getSecrets.outputs.BINGS-MAP-KEY }}" -var="mssql_server_administrator_login_password=${{ steps.getSecrets.outputs.MSSQL-SERVER-ADM-PASSWORD }}" || exit 0
        id: tfplan

  deploy:
    name: "Deploy"
    needs: preview
    # if: needs.preview.outputs.TFPLAN_EXITCODE != 2 # it is not part of the challenge, but nice to have
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Login to Azure with Service Principal
      # This step is not required by Terraform itself, but Terraform code contains resources with "az" commands to execute on agent locally.
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init -backend-config=resource_group_name="${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}" -backend-config=storage_account_name="${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config=container_name="${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}" -backend-config=key="${{ secrets.TFSTATE_KEY }}"

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="location=${{ secrets.LOCATION }}" -var="resources_prefix=${{ secrets.RESOURCES_PREFIX }}" -var="bing_maps_key=${{ needs.preview.outputs.BINGS-MAP-KEY }}" -var="mssql_server_administrator_login_password=${{ needs.preview.outputs.MSSQL-SERVER-ADM-PASSWORD }}"
